#ifndef DEFINITION_H
#define DEFINITION_H

enum commands_t {ADD_CONTENT, ADD_INVOICE, GET_CONTENT};
enum user_t {STUDENT, CONTENT_MANAGER, ADMINISTRATOR};
enum status_t {SUCCESS, ERROR, REQUEST};

#endif
